from datetime import datetime
from fpdf import FPDF

# pip install fpdf


class PayslipPDF(FPDF):
    def __init__(self, name, company, earnings, deductions, net_pay):
        super().__init__()
        self.name = name
        self.company = company
        self.earnings = earnings
        self.deductions = deductions
        self.net_pay = net_pay

    def header(self):
        # Add header to the PDF
        self.set_font("Courier", style='B', size=15)
        self.cell(190, 10, txt=self.company, ln=1, align='C')
        # self.set_font("Courier", size=12)
        # self.cell(190, 10, txt="Payslip", ln=1, align='C')

    def footer(self):
        # Add footer to the PDF
        self.set_y(-15)
        self.set_font("Courier", style='I', size=8)
        self.cell(0, 10, txt="Generated by Python", align='C')

    def add_employee_details(self):
        # Add employee name and other details
        self.set_font("Courier", size=12)
        self.cell(190, 10, txt="Name: " + self.name, ln=1, align='L')
        # Add other employee details if needed

    def add_earnings_deductions(self):
        # Add earnings and deductions table
        self.set_font("Courier", style='B', size=12)
        self.cell(95, 10, txt="Earnings", ln=0, align='L')
        self.cell(95, 10, txt="Deductions", ln=1, align='L')
        self.set_font("Courier", size=12)
        for earning, deduction in zip(self.earnings, self.deductions):
            self.cell(95, 10, txt=earning, ln=0, align='L')
            self.cell(95, 10, txt=deduction, ln=1, align='L')

    def add_net_pay(self):
        # Add net pay
        self.set_font("Courier", style='B', size=12)
        self.cell(190, 10, txt="Net Pay: " + self.net_pay, ln=1, align='R')
        
    def create_pdf(self):
        self.add_page()
        # self.header()
        self.add_employee_details()
        self.add_earnings_deductions()
        self.add_net_pay()
        # self.footer()

        current_date = str(datetime.now().date())

        self.output(self.name + "_Payslip_" + current_date + ".pdf", "F")

# Example data
earnings = ["Basic Pay: $1000", "Allowance: $200"]
deductions = ["Tax: $100", "Insurance: $50"]
net_pay = "$1150"
pdf = PayslipPDF("John Zane", "Acme Inc.", earnings, deductions, net_pay)
pdf.create_pdf()


# Name: John Doe
# Designation: Director
# Employee ID: 1234567
# Month: January 2023

# Earnings:

# Basic Salary: R100,000
# Housing Allowance: R15,000
# Travel Allowance: R10,000
# Total Earnings: R125,000
# Deductions:

# Tax: R20,000
# UIF (Unemployment Insurance Fund): R1,200
# Total Deductions: R21,200
# Net Pay: R103,800

# Note: This payslip is just a sample and does not reflect actual amounts. 
# Tax calculations and deductions may vary based on individual circumstances and the 
# current tax laws in South Africa.